#Week 2 Exercises

In this weeks exercises you will use Numpy/Scipy to impliment some numerical algorithms and then you will use Pandas to perform a rudamentary data analysis using the KDD 98 dataset.  Along the way you will use unix/basic python from the first week as well as git to save your work.

As a first step we import the libraries we'll use later on.  This allows us to use numpy library calls by prefixing the call with np.

In [3]:
#Import the libraries 
import numpy as np
import scipy as sp
import pandas as pd

##Matrix Manipulations
Lets first create a matrix and perform some manipulations of it.

Using numpy's matrix data structure, define the following matricies:

$$A=\left[ \begin{array}{ccc} 3 & 5 & 9 \\ 3 & 3 & 4 \\ 5 & 9 & 17 \end{array} \right]$$

$$B=\left[ \begin{array}{c} 2 \\ 1 \\ 4 \end{array} \right]$$

After this solve the matrix equation:
$$Ax = B$$

In [ ]:
#Problem 1

from numpy.linalg import inv
a = np.array([[3,5,9],[3,3,4],[5,9,17]])
b= np.array([[2],[1],[4]])
print a
print b
ainv=inv(a)
c= np.dot(a, b)
print c

Now write three functions for matrix multiply $C=AB$ in each of the following styles:

1. By using nested for loops to impliment the naive algorithm ($C_{ij}=\sum_{k=0}^{m-1}A_{ik}B_{kj}$)
2. Using numpy's built in martrix multiplication  
3. Using Cython

The three methods should have the same answer

In [96]:
#def multiplication (n)



#1) By using nested for loops to impliment the naive algorithm

result = np.full((10,10),0)
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j] += a[i][k] * b[k][j]
for r in result:
    print(r)

    

#2) Using numpy's built in martrix multiplication
    

a= np.full((10, 10), 7)
b= np.full((10, 10), 9)
c= np.dot(a, b)
print c




#Extra Practice Work    
#m=[[1,2,3,4,5], [11,12,13,14,15], [21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45],[51,52,53,54,55]]
#print m[1][:]
L=len(m[1][:]) ; H=len(m[:][1])
#print L, H
#i=0
#while i<:L
#    while x<len(:,1print i
#    print m[i]
#    i=i+1

[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
[[ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]
 [ 630.  630.  630.  630.  630.  630.  630.  630.  630.  630.]]

Now we wish to evaluate the performance of these three methods.  Write a method that given three dmiensions (a,b,c) makes a random a x b and b x c matrix and computes the product using your three functions and reports the speed of each method.

After this measure performance of each method for all $a,b,c \in \{10,100,1000,10000\}$ and plot the results.  Is one method always the fastest?  Discuss why this is or is not the case.

In [101]:
# just do 10, 100, 1000 with same number of field
#a= input ('Enter dimension a:')
#b= input ('Enter dimension b:')
#c= input ('Enter dimension c:')

a=10; b=10; c=10

m1= np.random.random((a, b))
m2= np.random.random((b, c))

**BONUS** Now repeat the past two problems but instead of computing the matrix product, compute a matrix's [determinant](http://en.wikipedia.org/wiki/Determinant).  Measure performance for matricies of various sizes and discuss the results.  Determinant may get impractical to calculate for not too huge of matricies, so no need to goto 1000x1000 matricies.

###IO Exercises

Below is a map of various datatypes in python that you have come across and their corresponding JSON equivalents.

$$Datatypes=\left[ \begin{array}{cc} JSON & Python3 \\ object & dictionary \\ array & list \\ string & string \\ integer	& integer \\ real number & float \\ true & True \\ false & False \\ null & None  \end{array} \right]$$


There are atleast two very important python datatypes missing in the above list. 
Can you find the same?  [list the two mising python datatypes in this markdown cell below]

1. 
2. 

Now We can save the above map as a dictionary with Key-value pairs 
1. create a python dictionary named dataypes, having the above map as the Key-value pairs with Python datatypes as values and JSON equivalents as keys.
2. Save it as a pickle called datatypes and gzip the same.
3. Reload this pickle, and read the file contents and output the data in the following formatted way as given in this example - "The JSON equivalent for the Python datatype Dictionary is Object". Output similarly for the rest of the key-value pairs.
4. Save this data as a JSON but using Python datatypes as keys and JSON equivalent as values this time.

In [ ]:
#1) Tuple
#2) Set

In [ ]:
#1)
import cPickle as pickle
import gzip
import shutil

dataypes={}
dataypes= {'array':'list','string':'string','integer':'integer','realnumber':'float', 'true':'True', 'false':'False', 'null':'None'}
print dataypes


#2) Save it as a pickle called datatypes and gzip the same
pickle.dump( dataypes, open( 'datatypes.p', 'wb' ))

with open('datatypes', 'rb') as f_in, gzip.open('datatypes.gz', 'wb') as f_out:
    shutil.copyfileobj(f_in, f_out)

#3) Reload this pickle, and read the file contents and output the data
datatypes = pickle.load( open( 'datatypes.p', 'rb' ) )

#for x in datatypes:
#    print (x)

for keys,values in datatypes.items():
    #print "The JSON equivalent for the Python datatype %d is %d" (values), (keys)
    #print (keys)
    #print (values)
    print "keys are",(keys)," values are",(values)

##Pandas Data Analysis
Pandas gives us a nice set of tools to work with columnar data (similar to R's dataframe). 
To learn how to use this it makes the most sense to use a real data set.
For this assignment we'll use the KDD Cup 1998 dataset, which can be sourced from http://kdd.ics.uci.edu/databases/kddcup98/kddcup98.html .


###Acquiring Data
First we pull the README file from the dataset into this notebook via the unix "curl" command.  Remember you can hide/minimize output cells via the button on the left of the output.

In [ ]:
!curl http://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/readme

As you can see this README describes several files which may be of use.  In particular there are two more documentation files (DOC and DIC) we should read to get an idea of the data format.  Bring these files into the notebook.

In [ ]:
!curl http://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/cup98dic.txt

Now we wish to download the cup98lrn.zip file and unzip it into a new subdirectory called "data".  
However, since this file is pretty big we don't want to store it on github.  
Luckily git provides the [.gitignore](http://git-scm.com/docs/gitignore) file which allows us to specify files we don't want to put into our git repository.

Please do the following steps:

1. Add the directory "data" to the .gitignore file
2. Commit the new .gitignore file
3. Create a new directory "data"
4. Download http://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/cup98lrn.zip into the data directory
5. Unzip the cup98lrn.zip (we will only be using the unzipped version, so feel free to remove the zip file)
6. Run "git status" to show that the data directory is not an untracked file (this indicates it is ignored)

**NOTE:** These steps only need to be run once, it is advised you comment all the lines out by putting a # at the start of each line after they have run.  This will save you time in the future when you have to rerun all cells/don't want to spend a few minutes downloading the data file.

In [ ]:
#1)
#!git rm --cashed data 
#!touch .gitignore
#added file manually to gitignore using sublime

#2) 
#!git add .gitignore
#!git status
#!git commit -m "this is the gitignore commit"

#3)
#!mkdir data

#4-5) was this support to be with unix? I did it with the GUI

#6)
#!git status
#Data file is still ignored

Now perform some basic sanity checks on the data.  Using a combination of unix/basic python answer the following questions:

1. How many lines are there?  
2. Is the file character seperated or fixed width format?
3. Is there a header?  If so how many fields are in it?
4. Do all rows have the same number of fields as the header?
5. Does anyhting in 1-4 disagree with the readme file or indicate erroneous data?

In [54]:
y[580]

'9501,CNT,2,MO,64050, , ,3801,0, , , , ,XXXX,C3,30,60,E,H, , , , ,,2,F,3,8,0,0,3,0,0,0,0,0,1,2,0,0,0,1,3,2,33,18,49,6,0,0, , , ,, , , , , , , , , , , , , , , , , , , , , ,1207,326,452,99,0,0,48,52,83,12,1,4,1,0,0,0,0,0,0,0,1,0,0,0,30,42,46,33,45,50,32,43,39,18,15,19,20,13,14,13,6,18,18,33,20,11,25,12,23,26,29,45,28,10,5,53,19,10,18,182,263,66,62,13,34,20,3,1,1,0,395,401,1,2,56,44,93,7,3,43,72,49,25,86,14,19,2,16,9,23,2,23,44,15,3,6,3,0,0,0,0,15,0,6,23,45,47,14,5,33,1,0,11,30,2,0,0,5,17,33,3760,157,616,185,243,218,251,8570,42,19,13,23,4,0,0,0,0,36,16,14,30,5,0,0,0,0,26,25,24,32,44,56,9,77,17,4,4,0,0,0,2,0,14,5,25,26,2,72,53,62,47,56,44,47,25,25,0,40,7,8,2,14,19,4,0,12,3,9,5,3,13,0,0,5,12,9,7,4,31,12,2,6,0,2,0,9,0,6,0,0,0,83,10,0,120,16,19,47,13,2,3,0,1,24,4,18,2,1,2,0,15,33,1,18,14,49,19,1,11,1,10,0,0,5,0,0,0,0,0,0,0,0,0,69,98,2,0,1,84,39,8,10,36,0,0,0,0,8,92,0,0,99,0,1,0,0,0,99,0,98,98,91,4,2,4,7,9706,9606,9604,,9603,9602,9601,9511,9510,9509,9508,,9506,,,9501,9412,,,,,,,L1F,A1F,A1F, ,N2F,N1D,N1D,N1D,N1D,N1D,N1D, ,F1D, , ,P1D,P1D, , , , , , ,8,9702,20,4,10,,,,,,,,9511,,,,,,,,9501,,,,,,,,,,,,,,15,,,,,,,,7,,,,,,,22,2,1,7,9501,15,9511,15,9511,9501,9511,10,11,101766,0,0,0,L,1,F,X,X,X,50,B\n'

In [3]:
#1
#!wc -l data/cup98lrn.txt

#2) 
#!head -1 data/cup98lrn.txt
#file is comma seperated "," delimited

#3)
#"Visual check"
#!head -1 data/cup98lrn.txt
#!sed -n '5p' < data/cup98lrn.txt


#3)
#x = open('data/cup98lrn.txt', 'r')
#y= x.readlines()
#cdel = y[1].split(',')
#print "Fields in the header=",len(cdel)



#4)  
#print "done"

#learn = pd.read_csv('data/cup98lrn.txt', error_bad_lines=False)
#learn.head(n=5)
#this tells you exactly which lines are


#4 Extra Work) 

#x = open('data/cup98lrn.txt', 'r')
#y= x.readlines()
#for i in y:
#    cdel = i.split(',')
#    if len (cdel) != 481:
#        print "Bad Rows:", i
#print 'Done Searching'

#print type(y[579])

#null = y[581]
#print null
#!pwd
#f = open('test-3.txt','w')
#f.write(null)
#for i in xrange(len(y)):
#    if(i<581):
##        f.write(y[i])
#    else:
#        break
#!cat test.txt
#for i in null:
    #print i
#    if i=='\0':
#         print i+"hi"
#print "done"
 
#pd.read_csv('test.txt')
        
    

#!awk -F',' 'END{Print NR}' data/cup98lrn.txt

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,...,0,0,L,4,E,X,X,X,39,C
1,9401,BOA,1,CA,91326,,,5202,0,,...,0,0,L,2,G,X,X,X,1,A
2,9001,AMH,1,NC,27017,,,0,0,,...,0,1,L,4,E,X,X,X,60,C
3,8701,BRY,0,CA,95953,,,2801,0,,...,0,1,L,4,E,X,X,X,41,C
4,8601,,0,FL,33176,,,2001,0,X,...,0,1,L,2,F,X,X,X,26,A

In [18]:
#!awk -F',' 'END{Print NR}' data/cup98LRN.txt

Give answers to questions 1-4 in this markdown cell:

1. 95413 rows in the file
2. Character Seperated with commas ","
3. Yes there is a header, with 481 columns
4. No some lines have null pointers! 
5. Yes the readme agrees with the data found, other than the lines that had errors. 

#README Reference: PKZIP compressed raw LEARNING data set. 
                Internal name: cup98LRN.txt 
                File size: 36,468,735 bytes zipped. 117,167,952 bytes 
                unzipped.
                Number of Records: 95412.
                Number of Fields: 481.

Now load the data file into a pandas data frame called "learn".  To save some time, we've loaded the data dictionary into col_types.  

Finally split learn into two data frames, learn_y: the targets (two columns described in the documentation) and learn_x: the predictors (everything but the targets)

In [40]:
#import numpy as np
#import scipy as sp
#import pandas as pd
#dict_file = open("data/dict.dat")
#col_types = [ (x.split("\t")[0], x.strip().split("\t")[1]) for x in dict_file.readlines() ]
#print col_types
#learn = pd.read_csv('data/cup98lrn.txt', error_bad_lines=False)
learn.head(n=30)

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,...,0,0,L,4,E,X,X,X,39,C
1,9401,BOA,1,CA,91326,,,5202,0,,...,0,0,L,2,G,X,X,X,1,A
2,9001,AMH,1,NC,27017,,,0,0,,...,0,1,L,4,E,X,X,X,60,C
3,8701,BRY,0,CA,95953,,,2801,0,,...,0,1,L,4,E,X,X,X,41,C
4,8601,,0,FL,33176,,,2001,0,X,...,0,1,L,2,F,X,X,X,26,A
5,9401,CWR,0,AL,35603,,,0,0,,...,0,0,L,1,F,X,X,X,16,C
6,8701,DRK,0,IN,46755,,,6001,0,,...,0,1,L,1,E,X,X,X,53,D
7,9401,NWN,0,LA,70611,,,0,0,,...,0,1,L,3,E,X,X,X,38,C
8,8801,LIS,1,IA,51033,,,0,0,,...,0,1,L,1,F,X,X,X,57,D
9,9401,MSD,1,TN,37127-,,,3211,0,,...,0,0,L,1,F,X,X,X,34,B
10,9601,AGR,0,KS,67335,,,0,0,,...,0,0,L,1,F,X,X,X,62,D
11,9601,CSM,1,IN,46220,,,2301,0,,...,0,0,L,2,F,X,X,X,23,B
12,8901,ENQ,0,MN,56475,,,2603,0,,...,0,1,L,4,D,X,X,X,57,D
13,9201,HCC,1,LA,70791,,,0,0,X,...,0,0,L,1,G,X,X,X,38,B
14,9301,USB,1,UT,84720,,,2709,0,,...,0,1,L,1,F,X,X,X,37,D
15,9401,FRC,1,CA,90056,,,0,0,,...,0,0,L,1,F,X,X,X,7,A
16,9401,RKB,0,MI,48067,,,5401,0,,...,0,0,L,2,F,X,X,X,27,A
17,8801,PCH,2,IL,62376,,,5201,0,,...,0,0,L,1,G,X,X,X,56,C
18,8601,AMB,28,FL,32810,B,,3601,0,,...,0,0,L,1,F,X,X,X,25,B
19,9501,L15,1,NC,27850,,,0,0,,...,0,0,L,1,F,X,X,X,61,C
20,8701,BBK,2,MN,55125,,,3601,0,,...,4,1,L,3,D,X,X,X,3,A
21,9601,L21,1,MI,49247,,,1601,0,,...,0,1,L,1,G,X,X,X,44,C
22,9401,SYN,0,FL,33983,,,0,0,,...,0,0,L,1,G,X,X,X,37,C
23,9301,L01,2,IL,60042,,,2311,0,,...,0,0,L,2,E,X,X,X,17,A
24,9501,MOP,0,MN,55044,,,5201,0,,...,0,1,L,3,E,X,X,X,5,A
25,9101,UCA,0,CA,93527-,,,4307,0,,...,0,0,L,2,F,X,X,X,42,B
26,9601,ESN,0,IL,60091,,,5601,0,,...,0,0,L,1,G,X,X,X,2,A
27,9201,L01,1,MO,64468,,,1401,0,,...,0,1,L,3,E,X,X,X,16,D
28,9101,IMP,0,TX,77381,,,4809,0,,...,0,1,L,2,E,X,X,X,15,A
29,9101,AVN,0,IL,62249,,,6001,0,,...,0,1,L,3,E,X,X,X,52,A

In [39]:



learn_y = learn[["TARGET_B"]+["TARGET_D"]]
learn_y.head(n=25)

    TARGET_B  TARGET_D
0          0         0
1          0         0
2          0         0
3          0         0
4          0         0
5          0         0
6          0         0
7          0         0
8          0         0
9          0         0
10         0         0
11         0         0
12         0         0
13         0         0
14         0         0
15         0         0
16         0         0
17         0         0
18         0         0
19         0         0
20         1         4
21         0         0
22         0         0
23         0         0
24         0         0

In [41]:
learn_x=learn 
del learn_x["TARGET_B"]
learn_x.head(n=5)

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,...,0,0,L,4,E,X,X,X,39,C
1,9401,BOA,1,CA,91326,,,5202,0,,...,0,0,L,2,G,X,X,X,1,A
2,9001,AMH,1,NC,27017,,,0,0,,...,0,1,L,4,E,X,X,X,60,C
3,8701,BRY,0,CA,95953,,,2801,0,,...,0,1,L,4,E,X,X,X,41,C
4,8601,,0,FL,33176,,,2001,0,X,...,0,1,L,2,F,X,X,X,26,A

In [2]:
one = df.groupby('letter')
mean= np.mean(learn, axis=0)
learn.iloc[0:3]
describe = learn.describe()

#for i in describe
#    print 
#print describe.index
#print describe.columns
#print describe

NameError: name 'learn' is not defined

###Summarizing Data
Now that we have loaded data into the learn table, we wish to to summarize the data.  
Write a function called summary which takes a pandas data frame and prints a summary of each column containing the following:

If the column is numeric:

1. Mean
2. Standard Deviation
3. Min/Max
4. Number of missing values (NaN, Inf, NA)

If the column is non alphabetical:

1. Number of distinct values
2. Number of missing values (NaN, INF, NA, blank/all spaces)
3. The frequency of the 3 most common values and 3 least common values

Format the output to be human readable.

For example:
> Field_1  
> mean: 50  
> std_dev: 25  
> min: 0  
> max: 100  
> missing: 5
>  
> Field_2  
> distinct_values: 100  
> missing: 10  
>  
> 3 most common:  
>   the: 1000  
>   cat: 950  
>   meows: 900  
>  
> 3 least common:  
>   dogs: 5  
>   lizards: 4  
>   eggs: 1

 #### Pandas excercises
 1. Selecting a subset of the rows using a condition
 1. Using Apply
 2. Different referencing of cells in dataframe: .log .iloc .ix direct
 2. Using multi-indexes, pivoting, stack unstack
 3. Using Groupby
 4. Pandas and matplotlib.

In [ ]:
#use transform to find the average